using System;

namespace LinqToImperative.ExprEnumerable
{
    /// <summary>
    /// An enumerable that is defined using expression trees rather than with C# code.
    /// </summary>
    internal interface IExprEnumerable
    {
        /// <summary>
        /// The types of elements generated by the enumerable.
        /// </summary>
        public Type ElementType { get; }
    }
}
