using System;
using System.Linq.Expressions;

namespace LinqToImperative.ExprEnumerable
{
    /// <summary>
    /// An enumerable that is defined using expression trees rather than with C# code.
    /// </summary>
    internal interface IExprEnumerable
    {
        /// <summary>
        /// The types of elements generated by the enumerable.
        /// </summary>
        public Type ElementType { get; }

        /// <summary>
        /// Visit any child expressions in the enumerable.
        /// </summary>
        /// <param name="visitor">The expression visitor.</param>
        /// <returns>The visited enumerable.</returns>
        public IExprEnumerable VisitChildren(ExpressionVisitor visitor);
    }
}
